name: flutter_ddd
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dartz: ^0.9.2
  device_info: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.19.2+1
  get_it: ^5.0.6
  http: ^0.12.2
  intl: ^0.16.1
  json_annotation: ^3.1.1
  package_info: ^0.4.3+4
  provider: ^4.3.0
  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.1
  #trust_fall: ^1.0.4
  uuid: ^2.2.0

dev_dependencies:
  build_runner: ^1.11.1
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1
  
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
