name: flutter_ddd
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dartz: ^0.9.2
  device_info: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_facebook_login: ^3.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.21.0+1
  get_it: ^6.0.0
  google_sign_in: ^5.0.1
  http: ^0.13.1
  intl: ^0.17.0
  json_annotation: ^4.0.1
  package_info: ^2.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  #trust_fall: ^1.0.4
  uuid: any

dev_dependencies:
  build_runner: ^1.11.1
  flutter_driver:
    sdk: flutter
  #flutter_test:
  # sdk: flutter
  json_serializable: any
  test: any

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
